Repository FastSubTeam/front, pull requests merged in 2023-08, with the labels that each got.

#42 Feat : 게시글 상세 페이지
  index.html
  src/components/community/CommentItem.tsx
  src/components/community/Comments.tsx
  src/components/community/NewComments.tsx
  src/components/community/PostEditor.tsx
  src/components/community/PostItem.tsx
  src/components/community/RenderHtml.tsx
  src/routes/Community.tsx
  src/routes/Post.tsx
  src/utils/community/timeFormat.ts
Labels: InProgress

#43 Feat: 전체 이벤트 검색 조회 메뉴바 생성
  src/components/events/EventList.tsx
  src/components/events/EventSearchBar.tsx
  src/data/address.ts
  src/data/constants.ts
  src/routes/events/Events.tsx
  src/states/AdressState.ts
  src/types/TAdressType.ts
Labels: Done

#46 feat: 등록된 모든 이벤트 조회 API 연결
  src/api/events/eventsRequests.ts
  src/components/EventLayout.tsx
  src/components/events/EventList.tsx
  src/components/events/EventSearchBar.tsx
  src/data/address.ts
  src/data/constants.ts
  src/types/IEvents.ts
Labels: Done

#44 [Feat] 관리자 수요조사 수정 기능 연동
  src/api/admin/adminRequests.ts
  src/data/modalData.ts
  src/routes/admin/AdminSurvey.tsx
  src/routes/admin/AdminSurveyDetail.tsx
  src/types/IAdminSurvey.ts
  src/types/IAdminSurveyRequest.ts
Labels: Done

#49 Feat/signup page
  package-lock.json
  src/App.tsx
  src/api/auth/signin.ts
  src/api/auth/signout.ts
  src/api/auth/signup.ts
  src/api/axios.ts
  src/assets/dummy-profile.png
  src/assets/popple.jpg
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/ui/Input.tsx
  src/components/ui/MyToast.tsx
  src/components/ui/Popple.tsx
  src/components/ui/Seletct.tsx
  src/components/ui/ValidationMessage.tsx
  src/contexts/UserContext.tsx
  src/data/constants.ts
  src/routes/Community.tsx
  src/routes/Home.tsx
  src/routes/SignUp.tsx
  src/routes/auth/ConfirmSignUp.tsx
  src/routes/auth/ForgotPassword.tsx
  src/routes/auth/Kakao.tsx
  src/routes/auth/SignIn.tsx
  src/routes/auth/SignUp.tsx
  src/types/ISignUp.ts
  src/utils/customToast.ts
Labels: Done

#51 Feat/logout
  src/api/auth/logout.ts
  src/api/auth/signout.ts
  src/components/Navbar.tsx
  src/routes/auth/SignUp.tsx
Labels: Done

#55 Feat/kakao login
  src/api/auth/kakao.ts
  src/components/Navbar.tsx
  src/components/ui/KakoaButton.tsx
  src/components/ui/LoadingSpinner.tsx
  src/index.css
  src/main.tsx
  src/routes/auth/Kakao.tsx
  src/routes/auth/SignIn.tsx
  src/routes/auth/SignUp.tsx
Labels: Done

#56 Feat/forgot password
  src/api/auth/forgotpassword.ts
  src/components/admin/AdminNav.tsx
  src/routes/auth/ForgotPassword.tsx
  src/routes/auth/SignUp.tsx
Labels: Done

#57 Feat/login page, 판매자 로그인 기능
  src/api/auth/signin.ts
  src/api/auth/signup.ts
  src/routes/auth/SignIn.tsx
Labels: Done

#58 [Feature] 수요조사 팝업 및 수요조사 참여 구현
  public/survey_bg.png
  public/survey_header.png
  src/App.tsx
  src/api/survey/surveyRequests.ts
  src/components/AdminLayout.tsx
  src/components/Layout.tsx
  src/components/survey/SurveyPopUp.tsx
  src/components/survey/SurveyRadioGroup.tsx
  src/components/ui/CheckBox.tsx
  src/components/ui/CommonModal.tsx
  src/data/constants.ts
  src/data/modalData.ts
  src/index.css
  src/routes/Home.tsx
  src/routes/survey/Survey.tsx
  src/types/ISurvey.ts
Labels: Done

#59 Feat: 셀러 행사 공고 등록 구현
  .gitignore
  src/App.tsx
  src/api/events/events.ts
  src/api/seller/postEvent.ts
  src/components/EventLayout.tsx
  src/components/events/EventList.tsx
  src/components/events/EventSearchBar.tsx
  src/components/seller/PostCategory.tsx
  src/components/seller/PostDesc.tsx
  src/components/seller/PostDropdown.tsx
  src/components/seller/PostEventName.tsx
  src/components/seller/PostForm.tsx
  src/components/seller/PostLocation.tsx
  src/components/seller/PostPeriod.tsx
  src/components/seller/PostTitle.tsx
  src/components/ui/Select.tsx
  src/data/postCategory.ts
  src/routes/auth/SignUp.tsx
  src/routes/seller/PostEvent.tsx
  src/states/PostEventState.ts
  src/types/IDateValue.ts
  src/types/IEvents.ts
  src/types/TPostEventType.ts
Labels: Done

#62 Feat: 로그인한 유저의 role에 따른 행사 등록 및 행사 페이지 수정
  src/api/events/event.ts
  src/api/events/events.ts
  src/api/seller/joinEvent.ts
  src/assets/login.jpg
  src/assets/survey_bg.png
  src/assets/survey_header.png
  src/components/Banner.tsx
  src/components/EventLayout.tsx
  src/components/events/EventDetail.tsx
  src/components/events/EventDetailBox.tsx
  src/components/events/EventDetailDesc.tsx
  src/components/events/EventDetailSeller.tsx
  src/components/events/EventJoinButton.tsx
  src/components/events/EventList.tsx
  src/components/seller/PostCategory.tsx
  src/components/seller/PostDesc.tsx
  src/components/seller/PostDropdown.tsx
  src/components/seller/PostEventName.tsx
  src/components/seller/PostForm.tsx
  src/components/seller/PostPeriod.tsx
  src/components/seller/PostTitle.tsx
  src/components/survey/SurveyPopUp.tsx
  src/data/constants.ts
  src/data/postCategory.ts
  src/routes/survey/Survey.tsx
  src/types/IEvent.ts
  src/types/IEvents.ts
Labels: Done

#63 [Feat] 수요조사 결과 목록 조회 및 차트 조회
  package-lock.json
  package.json
  src/App.tsx
  src/api/survey/surveyRequests.ts
  src/components/survey/SurveyBarChart.tsx
  src/components/survey/SurveyGroupChart.tsx
  src/components/survey/SurveyPieChart.tsx
  src/components/survey/SurveyPopUp.tsx
  src/components/survey/SurveyResultItem.tsx
  src/data/constants.ts
  src/data/modalData.ts
  src/routes/survey/Survey.tsx
  src/routes/survey/SurveyResultDetail.tsx
  src/routes/survey/SurveyResults.tsx
  src/types/IChart.ts
  src/types/ISurvey.ts
Labels: Done

#64 Feat/seller signup
  package-lock.json
  package.json
  src/api/auth/signup.ts
  src/hooks/useUser.ts
  src/routes/Home.tsx
  src/routes/auth/ConfirmSignUp.tsx
  src/routes/auth/Kakao.tsx
  src/routes/auth/SignIn.tsx
  src/routes/auth/SignUp.tsx
  src/types/ISignUp.ts
Labels: Done

#68 fix: env 재설정
  .env.d.ts
  src/components/events/EventMap.tsx
Labels: Improvements

#66 [Feat] 이미지 AWS S3 Upload 추가
  package-lock.json
  package.json
  src/data/s3configs.ts
  src/routes/Home.tsx
  vite.config.ts
Labels: Documentation

#69 Feat/myaccount 페이지 그리고 회원탈퇴 기능
  package-lock.json
  src/App.tsx
  src/api/auth/secession.ts
  src/components/Navbar.tsx
  src/components/auth/KakoaButton.tsx
  src/components/ui/Button.tsx
  src/components/ui/CommonModal.tsx
  src/components/ui/Input.tsx
  src/routes/auth/MyAccount.tsx
  src/routes/auth/SignIn.tsx
Labels: Done

#71 feat: 등록된 이벤트 수정 기능 추가
  src/App.tsx
  src/api/seller/modifyEvent.ts
  src/api/seller/postEvent.ts
  src/components/EventLayout.tsx
  src/components/events/EventButton.tsx
  src/components/events/EventDetail.tsx
  src/components/events/EventDetailBox.tsx
  src/components/events/EventDetailDesc.tsx
  src/components/events/EventDetailSeller.tsx
  src/components/events/EventList.tsx
  src/components/events/EventTitle.tsx
  src/components/seller/ModifyForm.tsx
  src/components/seller/PostCategory.tsx
  src/components/seller/PostDesc.tsx
  src/components/seller/PostDropdown.tsx
  src/components/seller/PostEventName.tsx
  src/components/seller/PostForm.tsx
  src/components/seller/PostLocation.tsx
  src/components/seller/PostPeriod.tsx
  src/components/seller/PostTitle.tsx
  src/components/ui/Participants.tsx
  src/components/ui/Title.tsx
  src/data/constants.ts
  src/main.tsx
  src/routes/Home.tsx
  src/routes/events/Events.tsx
  src/routes/seller/ModifyEvent.tsx
  src/states/Event.ts
  src/states/Events.ts
  src/types/IEvent.ts
  src/types/ITitle.ts
  src/types/TEventForm.ts
  src/types/TModifyEvent.ts
  src/types/TPostEventType.ts
Labels: Done

#75 feat: 이미지 첨부 추가, 북마크 기능 추가
  src/assets/default_thumbnail.jpg
  src/components/EventBanner.tsx
  src/components/events/EventDetail.tsx
  src/components/events/EventDetailBg.tsx
  src/components/events/EventDetailBox.tsx
  src/components/events/EventDetailDesc.tsx
  src/components/events/EventDetailSeller.tsx
  src/components/events/EventLayout.tsx
  src/components/events/EventList.tsx
  src/components/events/EventMap.tsx
  src/components/events/EventSearchBar.tsx
  src/components/seller/ModifyForm.tsx
  src/components/seller/ModifyImage.tsx
  src/components/seller/PostForm.tsx
  src/components/seller/PostImage.tsx
  src/components/ui/Hr.tsx
  src/components/ui/Status.tsx
  src/components/ui/Title.tsx
  src/data/modalData.ts
  src/routes/Home.tsx
  src/routes/events/Event.tsx
  src/types/IBookmarked.ts
Labels: Done

#79 feat: event part 스타일링 및 예외처리
  src/api/events/events.ts
  src/api/seller/cancelEvent.ts
  src/api/seller/deleteEvent.ts
  src/api/seller/joinEvent.ts
  src/api/seller/modifyEvent.ts
  src/api/seller/postEvent.ts
  src/components/events/EventButton.tsx
  src/components/events/EventDetail.tsx
  src/components/events/EventLayout.tsx
  src/components/events/EventList.tsx
  src/components/events/EventSearchBar.tsx
  src/components/seller/ModifyForm.tsx
  src/components/seller/PostForm.tsx
  src/components/ui/Container.tsx
  src/components/ui/Status.tsx
  src/data/modalData.ts
  src/routes/Home.tsx
  src/states/Events.ts
  src/types/IEvent.ts
  src/types/IEvents.ts
Labels: Done

#80 [Feat] 게시글 작성 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/community/postRequests.ts
  src/components/community/PostEditor.tsx
  src/components/community/PostItem.tsx
  src/data/modalData.ts
  src/routes/community/Community.tsx
  src/routes/community/Home.tsx
  src/types/IPost.ts
Labels: Done

#81 [Feat] 게시글 수정 삭제
  src/api/community/postRequests.ts
  src/components/community/PostEditor.tsx
  src/components/community/RenderHtml.tsx
  src/data/modalData.ts
  src/routes/community/NewPost.tsx
  src/routes/community/Post.tsx
Labels: Done

#82 Feature/protected routes
  package-lock.json
  package.json
  src/App.tsx
  src/api/admin/adminRequests.ts
  src/api/auth/userProfile.ts
  src/components/AdminLayout.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/admin/AdminLayout.tsx
  src/components/auth/BioTextarea.tsx
  src/components/auth/KakoaButton.tsx
  src/components/auth/ProfileImageUpload.tsx
  src/components/protectedRoutes/SigninRequireRoute.tsx
  src/components/protectedRoutes/SignoutRequireRoute.tsx
  src/data/constants.ts
  src/data/s3configs.ts
  src/routes/Home.tsx
  src/routes/auth/ConfirmSignUp.tsx
  src/routes/auth/EditUserInfo.hook.ts
  src/routes/auth/EditUserInfo.tsx
  src/routes/auth/ForgotPassword.tsx
  src/routes/auth/Kakao.tsx
  src/routes/auth/MyAccount.tsx
  src/routes/auth/SignIn.tsx
  src/routes/auth/SignUp.tsx
  src/types/ISignin.ts
Labels: Done

#84 [Fix] 커뮤니티 기능 충돌 해결
  src/App.tsx
  src/api/survey/surveyRequests.ts
  src/components/community/PostEditor.tsx
  src/components/ui/CommonModal.tsx
  src/data/modalData.ts
  src/routes/Home.tsx
  src/routes/community/Community.tsx
  src/routes/community/Post.tsx
Labels: Bug, Done

#85 feat: 뷰티스토어 조회 -> 등록된 커뮤니티 글 간략 조회 변경
  src/components/events/EventDetail.tsx
  src/components/events/EventDetailBox.tsx
  src/components/events/EventLayout.tsx
  src/components/events/EventList.tsx
  src/components/ui/Status.tsx
  src/data/constants.ts
  src/routes/Home.tsx
Labels: Done
